### ISSUE TITLE
Feature Request: sort hostfile output in a hierarchical order

### ISSUE THREAD

**Issue by jawz101** [funilrys/PyFunceble#10]
The app currently sorts the domains in alphabetical order but I was wondering if it would be more readable in a hierarchical order.

[example host file ](https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts)sorted with domain hieararchical order.

So if I have a full domain and its subdomains as AAAA.BBBB.CCCC.DDDD.TLD
instead of sorting it purely like that I'd sort by DDDD then CCCC,BBBB,AAAA and finally the TLD.  This puts all of the subdomains grouped together in the list.

instead of all of google's entries spread all over a host file they'd get clumped together based on the google.com domain.
```
0.0.0.0 adservice.google.com
0.0.0.0 googleadapis.l.google.com
0.0.0.0 s0-2mdn-net.l.google.com
0.0.0.0 ssl-google-analytics.l.google.com
0.0.0.0 www-google-analytics.l.google.com
0.0.0.0 pagead2.googleadservices.com
0.0.0.0 partner.googleadservices.com
0.0.0.0 www.googleadservices.com
0.0.0.0 googleadservices.com
0.0.0.0 ssl.google-analytics.com
0.0.0.0 www.google-analytics.com
0.0.0.0 google-analytics.com
0.0.0.0 chart.googleapis.com
0.0.0.0 ad-creatives-public.commondatastorage.googleapis.com
0.0.0.0 imasdk.googleapis.com
0.0.0.0 ade.googlesyndication.com
0.0.0.0 pagead2.googlesyndication.com
0.0.0.0 tpc.googlesyndication.com
0.0.0.0 www.googletagmanager.com
0.0.0.0 www.googletagservices.com
0.0.0.0 redirector.googlevideo.com
```

**Comment by funilrys** [comment]
Hi @jawz101 and thanks for opening thing issue.

Indeed it's may be a good idea to introduce such feature.

**Comment by funilrys** [comment]
Note: Do not take it personally if I'm not starting to code this feature yet.

I'm currently writing all inline comments but will think about this implementation once I'm done with all inline comments. :+1:

**Comment by jawz101** [comment]
No problemo.  I just like writing my thoughts out & if someone thinks it's interesting and don't require much implementation/maintenance- that's cool.  If not, that's cool too :)

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/5fb252e225062acbe8bf7f1d469e3d3b8c08b8fd.

**P.S: Please DO NOT close this issue manually. 
This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/5fb252e225062acbe8bf7f1d469e3d3b8c08b8fd will be merged to the `master` branch.**

**Comment by jawz101** [comment]
Very cool!

**Comment by funilrys** [comment]
Hi @jawz101,

I consider that if someone give an idea and that idea finish in the code base, that person indirectly contributed to the evolution of the code base. So those people should be in the list of contributor. The fact is that your idea made or make the code base a better one.

So I'm not going to change that today or in the future.
I do think that it is what makes open source code stronger than proprietary source source. Everybody has its place here, no need to code!

**Comment by jawz101** [comment]
```
  --hierarchical        Switch the value of the hierarchical sorting of tested
                        file. Configured value: True
```

is it really defaulted to true? I'm not seeing them sort

**Comment by funilrys** [comment]
Hi @jawz101, I was thinking about setting it to default... But I'll have to rethink about that as I'll release 1.0.0 very soon... 

Anyway, you found a bug in the CLI parser :+1:

**Comment by jawz101** [comment]
It doesn't look like the sort does what I imagine

[hosts.txt](https://github.com/funilrys/PyFunceble/files/2715036/hosts.txt)

Example: content.ad should be down with other domains that begin with a 'C'.  Maybe this is a little awkward of a request

**Comment by funilrys** [comment]
Hi @jawz101,

Let me explain what I did.

Let's say we have `aaa.bbb.ccc.com`

What I basically do (internally) is suppress all punctuation and reorder the elements of the given domain/IP in order to then sort alphabetically. Once it's done the hierarchy is kept as we read internally in the generated order but test the original domains.

It can be strange or weird but it works :smile: 

So I first reorder by TDL which means that if `com` is the tdl I sort in the following order.
* `com`
* `aaa` 
* `bbb`
* `ccc`

That gives us 2 domains. The one we are currently testing `aaa.bbb.ccc.com` and the one which gives us the testing order (if we have to sort hierarchically naturally) `comaaabbbccc`.

But, if `ccc.com` is registered into the [PSL](https://github.com/publicsuffix/list) which we parsed into [`public-suffix.json`](https://github.com/funilrys/PyFunceble/blob/master/public-suffix.json) we sort in the following order.

* `ccc`.`com`
* `aaa`
* `bbb`

That gives us 2 domains. The one we are currently testing `aaa.bbb.ccc.com` and the one which gives us the testing order (if we have to sort hierarchically naturally) `ccccomaaabbb`.

Same if `bbb`.`ccc`.`com` is registered we sort in the following order.

* `bbb`.`ccc`.`com`
* `aaa`

Which gives us `aaa.bbb.ccc.com` to test and `bbbccccomaaa` as the order giver.

That way it stay hierarchically sorted. 
Applied to a big list it gives us what you got.


If I misunderstood something and you need another kind of sorting, please let me know, I'll be glad to implement it :smile_cat: 

Cheers,
Nissar

**Comment by jawz101** [comment]
Ah... so it looks like it sorts by the public suffix list 1st and then the remainder.

This is really just a puzzle more than anything so I'm glad you think it's interesting too.

My method didn't really account for the entire PSL, but what I do might be something like

Part 1 - Grab the PSL
Part 2 - Grab the next domain part to the left of it
Part 3 - Take the rest

Then sort by Part 2, Part 3, Part 1

So, for example, google's would be together:
googleadservices.ru, googleadservices.nl, adservice.google.de googleadservices.co.uk, adservice.google.com.tr, googleadservices.com, etc. would sort've clump together

**Comment by funilrys** [comment]
Hi @jawz101, I just implemented your method with the following order:

* Part 2
* Part 1
* Part 3

**P.S: Please DO NOT close this issue manually. 
This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/7a273bb25ca7adac8e27f8c057450fad1d81f79d will be merged to master.**

**Comment by jawz101** [comment]
Awesome! I hope it made sense.  That should be a nice way to see a company's domain presence on the web.
