### ISSUE TITLE
Doc: @control-whois-storage `--store-whois`

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#108]
This part of the documentation is rather unclear about what is stored or not.

part: <https://github.com/funilrys/PyFunceble/blob/control-whois-storage/docs/usage/from-a-terminal.rst#--store-whois>

If you keeps `--store-whois` as `False` is the bare minimum like dates(created,changed,expired), dns, who? stored

If `--store-whois` = `true` are you then keeping the complete `whois` print inclusing all the data you could template from `.TLD`

**Comment by funilrys** [comment]
@spirillen I think I forgot my warning from https://github.com/funilrys/PyFunceble/blob/control-whois-storage/docs/configuration/core.rst#store_whois_record

But yes.

`store_whois_record` is set by default to `False`. That means that it will store the expiration date and subject (the system still uses/needs them) but not the full WHOIS record.

If you looked at the new (SQL) database structure, it is the `record` column of the `pyfunceble_whois_record` table.

There is indeed room for improvement here 🤔

**Comment by spirillen** [comment]
Hey @funilrys could you try dump a few sql records of each switches? That might help me in writing the docs to see the full picture by my self.

As you know from our keybase conversation I'm still converting to the new structure, so can't currently put up a test bench

**Comment by funilrys** [comment]
Before migration to SQLAlchemy:
![2020-08-22_17-17](https://user-images.githubusercontent.com/14127285/91561661-44cfcc80-e93c-11ea-99c6-643aec8b5fd1.png)

After migration to SQLAlchemy:
![2020-08-22_17-23](https://user-images.githubusercontent.com/14127285/91561655-439e9f80-e93c-11ea-9f7b-4de477214293.png)


Without `--store-whois` or better said with `store_whois_record` set to `False`:
(The missing one is because I removed it from the list to reduce the waiting time while testing other things)
![2020-08-28_14-47](https://user-images.githubusercontent.com/14127285/91562449-8319bb80-e93d-11ea-9dbe-4f3f5d480110.png)

With `--store-whois` or better said with `store_whois_record` set to `True`:
![2020-08-28_14-49](https://user-images.githubusercontent.com/14127285/91562643-cffd9200-e93d-11ea-9e75-ca1f4cc71455.png)

**Comment by spirillen** [comment]
I believe this issue should have been closed with c199b1d 

Can you agree with that @funilrys ?

**Comment by funilrys** [comment]
Agree.
