### ISSUE TITLE
Github Actions support

### ISSUE THREAD

**Issue by asaddon** [funilrys/PyFunceble#135]
If possible please add support of Github Actions, or if it's already working then either add it in the documentation or guide me to a working repository already using GutHub actions so that I can take a look myself, I've tried for hours before opening this feature request and I always get stuck at this error in Github Actions and I can't seem to find a way to fix it.
Thank you!

'/home/runner/.config/PyFunceble/.PyFunceble.yaml' was not found.
raise FileNotFoundError(self.path_to_config)
FileNotFoundError: /home/runner/.config/PyFunceble/.PyFunceble.yaml

**Comment by spirillen** [comment]
Could you share the link to the log files / repo, and I'll have a look, But up front I'll suggest you would try to specify the pyfunceble.yml location according to the docs `PYFUNCEBLE_CONFIG_DIR` <https://pyfunceble.readthedocs.io/en/master/components/environment-variables.html?highlight=PYFUNCEBLE_CONFIG_DIR#what-do-we-use-and-why>

**Comment by asaddon** [comment]
@spirillen Thankyou so much, setting up the environment variable worked perfectly, somehow I missed that while searching for a solution and didn't realize PyFunceble supported that 👍

**Comment by spirillen** [comment]
> @spirillen Thankyou so much, setting up the environment variable worked perfectly, somehow I missed that while searching for a solution and didn't realize PyFunceble supported that +1

Don't worry, it is one of those things (sections) we will have to relocate in the new docs :+1:

**Comment by asaddon** [comment]
>By the way... I'll suggest to change this line to use the @dev temponary until we hit the dev releases of version 4.x

Done👍

>You can also skip this step

I've changed it now, I used that workaround a while ago when I was using Travis CI and at that time for some reason Travis CI was not playing well with full URI's.

**Comment by spirillen** [comment]
@funilrys don't forget to move the Global Variables to the CI section within the docs for version 4

**Comment by funilrys** [comment]
@spirillen, can you clarify what I am missing here ?

**Comment by spirillen** [comment]
Note: haven't checked current doc for v4 about this yet, but to tell what it is about

It's about the Global Environment Variables <https://pyfunceble.readthedocs.io/en/master/components/environment-variables.html?highlight=PYFUNCEBLE_CONFIG_DIR#what-do-we-use-and-why> which for at least v3 is hidden beneath the `components/`section, rather than under (or link to) the CI variables, which seems like the more fitted place to hold the information. As they are more related to any scripts than under the component section.

So my suggestion is simply to move the `environment-variables.rst` to the CI|scripts section. 

Why, every time I have to lookup any of these, I simply have to do a search to locate them and as this ticket reviles as well, other troubles finding them as well if even.

Just checked, still under components. <https://pyfunceble.readthedocs.io/en/4.0.0-dev/components/environment-variables.html?highlight=environment%20variables>

**Comment by funilrys** [comment]
Just a side note, I just integrated the support for GitHub Actions. Feel free to follow https://github.com/PyFunceble/ci_test/blob/master/.github/workflows/main.yml for an example of how you can configure it.

**Comment by spirillen** [comment]
Should be fixed with https://github.com/spirillen/PyFunceble/pull/25

**Comment by spirillen** [comment]
- [x] In progress https://github.com/funilrys/PyFunceble/projects/7#card-51840757
  - [ ] Done https://github.com/funilrys/PyFunceble/projects/7#card-51840757
