### ISSUE TITLE
Obfuscating the /home/username path with system variable for user path

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#141]
**Is your feature request related to a problem? Please describe.**
See title

**Describe the solution you'd like**
Obfuscating the `/home/SomeRealUserName` with default system variables as `$HOME` in log outputs 

This will help protect the real identity of a user, hence lift the level of privacy from a copy/paste interaction

**Comment by spirillen** [comment]
APPENDIX 1:

Maybe only use relative path in output rather than full path?

**Comment by funilrys** [comment]
The output directory can virtually be everywhere!!

**Comment by funilrys** [comment]
This is going to be a nightmare to write because of the cross-platform (*nix, macOS, windows, ...) support but there has to be a way to do this. 

The reason, I had that path explicitly, is because I'm thinking a bit ahead of what is coming. For example: How to know which data are from a single file in the filesystem the day we will have to play with an API that virtually anybody can use to retrieve its own data.

**Comment by funilrys** [comment]
I really don't want to force everyone to use a special PyFunceble directory location in their filesystem. 
Therefore the full path. But I'm willing to make a concession on the storage of the full path in order to protect the real identity of a user. 

By the way: In a traceback, we can't change the full path.

**Comment by spirillen** [comment]
I know, that's why I was a bit un-precise in my suggestion, as this need to be thought throug before programming

**Comment by funilrys** [comment]
Closing because of #215.
