### ISSUE TITLE
Domain Syntax test not 100% accurate

### ISSUE THREAD

**Issue by speedmann** [funilrys/PyFunceble#17]
**Describe the bug**
When testing for domain syntax a valid case is rejected with "INVALID".

**Modifications under `.PyFunceble.yaml`**
None

**To Reproduce**
```
$ pyfunceble -d google.de. -s
google.de. INVALID
```

```
$ curl google.de.
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.de/">here</A>.
```

**Expected behavior**
Domains ending with a dot are verified valid and tested if they are available

**Versions (please complete the following information):**
 - OS: macos mojave
 - Python Version: 3.6.7
 - PyFunceble Version: pyfunceble 1.3.0. (Blue Bontebok: Dragonfly)

**Additional context**
I guess this is nitpicking over what is a valid domain syntax and what not. Also the mentioned syntax might be quiet uncommon.
But if syntax validation is offered, the check should return reliable results. 
Additional Information http://www.dns-sd.org./TrailingDotsInDomainNames.html

**Comment by funilrys** [comment]
Hi @speedmann, 
Thanks for the feedback! I forgot about those one.

Will fix asap!

Cheers,
Nissar

**Comment by funilrys** [comment]
Fix introduced with https://github.com/funilrys/PyFunceble/commit/2fce8b632e61c614fafaae83baf142dcdc7a7665.

*It's now available in the `dev` version.*

**P.S: Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/2fce8b632e61c614fafaae83baf142dcdc7a7665 will be merged to master/stable version.**
