### ISSUE TITLE
no_special vs --special-lookup

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#184]
Since v4.x the syntax have changed for special rules.

```rst
:code:`-ns|--no-special`
    .. deprecated:: 4.0.0

    Replaced by `--special-lookup <index.html#special-lookup>`_
```

But in the `.PyFunceble_production.yaml` they are still called by `no_special` this seems unlogick. At best I'll suggest it stays for backward capability but it's equivalent will find it's way into the yaml: `special-lookup`

https://github.com/funilrys/PyFunceble/blob/c8bca124c40858fd3586145a129c5c2f1c9a962e/.PyFunceble_production.yaml#L68

**Comment by spirillen** [comment]
Doc relation:
  - [ ] https://github.com/spirillen/PyFunceble/issues/33
  - [ ] https://github.com/spirillen/PyFunceble/issues/33

**Comment by funilrys** [comment]
@spirillen you are referencing the wrong file. That file in the root of the project is still in there because we want the older version to still work.
Since `4.0.0a1` it is in there: https://github.com/funilrys/PyFunceble/blob/0d5e5450473aff6712277d8dd0bbc240e2f953f1/PyFunceble/data/infrastructure/.PyFunceble_production.yaml#L194

**Comment by funilrys** [comment]
The difference (technically): The new version is delivered with the PyPI package (itself). 

Meaning that it is bound to the deployed version. Also meaning that we don't need to download them, they are delivered with your `pip install` 😄.

Finally, there is obviously no need to download the latest configuration from here (since `4.0.0a1`). So no more break or issues after each push out here.

**Comment by spirillen** [comment]
Super... I'll fic it up in the docs... Working on https://github.com/spirillen/PyFunceble/issues/24 right now :smiley:
