### ISSUE TITLE
preload use relative path

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#215]
**Is your feature request related to a problem? Please describe.**
Let's use a live example <https://github.com/mypdns/porn-records/blob/43efb7722cb785a97539a0cb745e2d45089667c9/active_domains/output/domains.list/preload.json>

When we look at the file will notice, pyfunceble are using full path
```json
    "abs_source": "/home/runner/work/porn-records/porn-records/submit_here/adult.mypdns.cloud/domains.list",
    "output_dir": "/home/runner/work/porn-records/porn-records/active_domains/output/domains.list",
    "rel_source": "submit_here/adult.mypdns.cloud/domains.list",
    "source": "/home/runner/work/porn-records/porn-records/domains.list",
    "subject": "/home/runner/work/porn-records/porn-records/submit_here/adult.mypdns.cloud/domains.list",
```

**Describe the solution you'd like**
Use relative path, so both a ci/machine.x can use the same preload.json to continue a work. as the `rel_source`

If this is already the case by using the `rel_source` as first choice for continue a work, this issue is closed.

For other readers, I'm keeping my nose out of the code, to be able to make better docs, and not getting to technically within them.

**Comment by funilrys** [comment]
I somehow want to remove the absolute path because it makes it nearly impossible to continue a job from another machine, network, or infrastructure. It is in my backlog. But I have to focus on some side but PyFunceble related project too.

So, in the near future, this won't be an issue once I'm getting away from the absolute path. 

But don't expect it to be as fast as other migration. Such conversion (especially the `source` or `destination` in the datasets) will be done step by step over time while retesting.
