### ISSUE TITLE
Print execution time into percentage.txt output file

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#31]
**Is your feature request related to a problem? Please describe.**
Would be a nice feature to have the execution time recorded into the percentage.txt file.

**Describe the solution you'd like**
Just print the final execution time from the `-ex` paramater into the percentage.txt file as in screengrab below shown from console.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2019-05-26_16-49-37](https://user-images.githubusercontent.com/9961541/58383385-607c5280-7fd6-11e9-8f8e-f89e5e0922a3.png)

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/bfb43b0830ddddbe383ade48186b31d8bd198fa2.

**P.S: Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/bfb43b0830ddddbe383ade48186b31d8bd198fa2 will be merged to master.**
