### ISSUE TITLE
FEATURE: Sql retry re-connection

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#313]
## Description
As my sources for testing I rather (to) big to be handle by CSV files do to the disk I/O I usual prefer using the SQL backend, but unfortunately, then only all to often I get ...

```python
Fatal Error: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (ConnectionResetError(104, 'Connection reset by peer'))")

File "/home/spirillen/.local/lib/python3.10/site-packages/pymysql/connections.py", line 759, in _write_bytes
raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionResetError(104, 'Connection reset by peer'))")
```

Or similar connection related drops, and the test stops do to the error.

## Possible Solution
Let sqlalchemy retry to reconnect x number of times before actually failing.

In the above example, it was a simple local lock on the process that maid this happens. Other times it is a system update that causes this or even a network package that have gone away, the reasons is many.

I believe having a randomly delayed re-connection could help a lot here

## Considered Alternative
Use more than a week for testing my anti porn project files with CSV backend

**Comment by funilrys** [comment]
So, from my understanding without actually testing it, to solve this I have to go back to connection pooling. Which is by definition disabled for us because I use:

https://github.com/funilrys/PyFunceble/blob/3227499d7d722e684a85f62926e89237abfdaf6e/PyFunceble/database/session.py#L170-L184

Instead of https://github.com/funilrys/PyFunceble/blob/3227499d7d722e684a85f62926e89237abfdaf6e/PyFunceble/database/session.py#L188-L199

at:

https://github.com/funilrys/PyFunceble/blob/3227499d7d722e684a85f62926e89237abfdaf6e/PyFunceble/cli/processes/workers/base.py#L134 .

One way to solve this is to add the `pool_pre_ping` argument to `sqlalchemy.create_engine` method. But it will only work when a pool is active.

Note to self: https://docs.sqlalchemy.org/en/14/core/pooling.html

**Comment by spirillen** [comment]
Will get back on this, when I'm able to do some real testing.

**Comment by spirillen** [comment]
Can't continue this thread, thanks to GH's decision on demanding spyware to login from today and forward
