### ISSUE TITLE
FEATURE: Special Rules for imgur.com

### ISSUE THREAD

**Issue by smed79** [funilrys/PyFunceble#319]
**①** - deleted / removed **imgur.com** images are shown by PyFunceble as **ACTIVE**.

```
$ PyFunceble -u https://i.imgur.com/yDoCnHk.png

Subject                             Status        Source
------------------                  -----------   ----------
https://i.imgur.com/yDoCnHk.png     ACTIVE        HTTP CODE
```
```
$ curl -I https://i.imgur.com/yDoCnHk.png

HTTP/2 302 
location: https://i.imgur.com/removed.png
```
---
**②** - unexisting **user** custom domain is shown by PyFunceble as **ACTIVE**.

```
$ PyFunceble -u https://vh7faflpemfm.imgur.com/

Subject                             Status        Source
------------------                  -----------   ----------
https://vh7faflpemfm.imgur.com/     ACTIVE        HTTP CODE
```
```
$ curl -I https://vh7faflpemfm.imgur.com/

HTTP/2 301 
location: https://imgur.com/user/vh7faflpemfm
```

**Comment by funilrys** [comment]
@smed79 there is nothing we can do for your second case. 

- I can flag `https://vh7faflpemfm.imgur.com/` as `INACTIVE` because it redirects to `https://imgur.com/user/vh7faflpemfm`
- But I can't flag `https://imgur.com/user/vh7faflpemfm` as `INACTIVE` if the user doesn't exist because imgur.com is showing a `404` page but the status code is still `200`. And there is nothing to parse because it's a SPA that loads its content when javascript spins up.
