### ISSUE TITLE
Url Testing --url-file marking domains with port numbers like :80 :81 :8080 etc as INVALID

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#32]
**Is your feature request related to a problem? Please describe.**
Url testing marks links with port numbers after the domain name like :80 :81 :8080 etc are marked INVALID and never tested
https://github.com/mitchellkrogza/Phishing.Database/tree/master/phishing-links/output/domains/INVALID/list

**Describe the solution you'd like**
Test all links that include a random port number

**Describe alternatives you've considered**

**Additional context**

**Comment by funilrys** [comment]
Fix introduced with https://github.com/funilrys/PyFunceble/commit/b2a40b76a64f0f7fadb80fdda2b604af33ea6947.

**P.S: Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/b2a40b76a64f0f7fadb80fdda2b604af33ea6947 will be merged to master.**
