### ISSUE TITLE
Print version of PyFunceble into percentage.txt file

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#33]
**Is your feature request related to a problem? Please describe.**
Would be useful to have version number printed into the percentage.txt file helpful for diagnosing big time differences between tests and versions of dev.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by funilrys** [comment]
Feature introduced with https://github.com/funilrys/PyFunceble/commit/aed78b543f1fc4679d005ceba42dd5a6e247d162.

**P.S: Please DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/aed78b543f1fc4679d005ceba42dd5a6e247d162 will be merged to master.**
