### ISSUE TITLE
ANNOIANCE | "cc @sjhgvr" in dead-hosts/domain_blocklist_web_dbl-oisd-nl Final/Result

### ISSUE THREAD

**Issue by sjhgvr** [funilrys/PyFunceble#402]
### What is the problem you are experiencing?

This issue is personal to me, as only I'm being spammed by email because of "@sjhgvr" in the title of each update of "dead-hosts/domain_blocklist_web_dbl-oisd-nl Final/Result"

![image](https://github.com/user-attachments/assets/26e388bd-06ee-4cad-b97a-43403186ec29)

I've set up a filter so those mails are automatically trashed, but I feel it's better to have the issue fixed @ source.

Please remove "@sjhgvr" from the title.

Thank you

**Comment by spirillen** [comment]
Hi @sjhgvr Please open your issue here: https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl/issues

This is "only" the program used for testing, The test process is done from the infrastructure of https://github.com/dead-hosts and in this specific cases https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl/issues

![image](https://github.com/user-attachments/assets/f8245a40-8fbc-46fd-8a60-c81fd423eb2c)

**Comment by spirillen** [comment]
This PR should solve it https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl/pull/4

**Comment by sjhgvr** [comment]
> Hi @sjhgvr Please open your issue here: https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl/issues

Makes sense, my appologies.
Should I however still do that, considering the following;

> This PR should solve it https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl/pull/4

?

**Comment by spirillen** [comment]
I would, and then mention the PR

**Comment by funilrys** [comment]
Sorry for the annoyance while integrating with the incoming platform. With https://github.com/dead-hosts/infrastructure-launcher/commit/cb07944fe59cc9849157c4269adcbc57d8761cd5 , ping will have to be activated pro-actively. 

Thank you for taking the time to report. 

Let me know if you need something else.
