### ISSUE TITLE
Feature Request | Special Rule, set records starting with www as invalid

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#410]
### What is the feature you'd like to request?

As of working with #407, #408 and #409 It comes to my attention, that some of the free hosting services are redirecting all requests starting with `www.example.com` to `example.com`

With this in mind + #409 I would suggest we make a equal list as the special rules for such domains, and set them INVALID as they have no place on this earth.

### What problem are you trying to solve?

Here I have a few domains like tumblr, `blogspot.com`, and `vercel.app`

Some "maintainers" are headlessly just adding the www suffix to any of there records, as seen with https://kb.mypdns.org/issue/MTX-1402

### What solution would you like to see?

Set any domains stating with `www.` as invalid for domain `example.com`

### Are there any alternatives you've considered?

Individual scripts domain this, but kind a removing the idea for many of the already builtin feature for testing & import third party lists.

### Additional context

Bump...

Bump...

Bump...

Bump...

Bump...

**Comment by funilrys** [comment]
>  set them INVALID as they have no place on this earth.
> Set any domains stating with www. as invalid for domain example.com

No. In another universe maybe.
I sometime work with some old entities that does both, based on the feeling of the admins/devs or the color of the sky. That's why we have the `--complement` option. To allow maintainers to test both. 

I can't accept this feature request.

For more context:
I see and know some _(undisclosable due to NDA)_ entities that do redirect to `www.example.org` to `example.org`, but somedays because they are testing some new infrastructure or source code, they will do the other way around (`example.org` to `www.example.org`) for 1% or N% of their traffic based on some weird redirection path. 
See it like advanced port knocking/firewalling, but for a few percentage of traffic.

**Comment by funilrys** [comment]
btw, even in 2024, there is still a lot of website that does only work on `www.example.org` ... That's another reason.

**Comment by spirillen** [comment]
> I see and know some (undisclosable due to NDA) entities that do redirect to www.example.org to example.org

You have misunderstood the request then.  This should be an addition to the special rules, that are managed alongside with the special rule.

Let take `tumblr,com`, they uses `$usernam.tumblr,com`, but not `www.$usernam.tumblr,com`, they do however respond to www,. but are redirected to none www.

So the [rules.py](https://github.com/funilrys/PyFunceble/blob/dev/PyFunceble/checker/availability/extras/rules.py) for tumblr, would then be something like

```python
r"\.tumblr\.com$": [
    (self.switch_to_down_if_status_code, 404),
    self.www,
    ],
```

Meaning all records with `www.$usernam.tumblr,com` are marked invalid

**Comment by funilrys** [comment]
That's what we do, but we flag them as `INACTIVE`. 

https://github.com/funilrys/PyFunceble/blob/06426c7046e5d5cb7166271cb98bbfdf568a0332/PyFunceble/checker/availability/extras/subject_switch.py#L63-L72

**Comment by spirillen** [comment]
> That's what we do, but we flag them as INACTIVE.

should be

> That's what we do, but we flag them as INVALID.
