### ISSUE TITLE
Failing after few test

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#56]
## Bug description
The best and shortest way is simply having a look at these Travis builds that completly fails after a few test

https://travis-ci.com/Import-External-Sources/pornhosts/builds/136599212

https://travis-ci.com/Import-External-Sources/google.tld/builds/136245802

https://travis-ci.com/Import-External-Sources/google.tld/builds/136310675

https://travis-ci.com/Import-External-Sources/google.tld/builds/136436604

https://travis-ci.com/Import-External-Sources/google.tld/builds/136549183

## Expected behavior**
Running as usual

**Comment by funilrys** [comment]
Fixed by https://github.com/funilrys/PyFunceble/commit/3fbb8cd3c654968250ea2d8b90f4f197ca5c112f.

It should be deployed in the next 30 minutes.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/3fbb8cd3c654968250ea2d8b90f4f197ca5c112f will be merged to master.**

**Comment by funilrys** [comment]
For those asking why it takes so many times for deployment: https://travis-ci.com/funilrys/PyFunceble

**Comment by funilrys** [comment]
For those asking why it takes so much time on OSX...

From the [multiprocessing documentation](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods):
> Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See [bpo-33725](https://bugs.python.org/issue33725).
