### ISSUE TITLE
Possible inclusion of AlienVault's IP reputation data checking

### ISSUE THREAD

**Issue by ScriptTiger** [funilrys/PyFunceble#68]
IP reputation is a lot more dependable than domain name reputation. As we all know, there are literally millions of domain name blacklists and whitelists floating around on the Web, each of which possibly containing literally millions, tens of millions, or even hundreds of millions of entries. However, many of these domain names can be traced back to duplicate IP addresses and there is a much smaller list of bad IPs versus bad domain names. Maybe resolving domain names to IPs and checking AlienVault's IP reputation data would also be helpful at some stage, and also noticing whether or not an IP has been removed from that list or not, in order to add another dimension to curation.

http://reputation.alienvault.com/reputation.data

I know that over time they do add and remove entries and it is curated to a degree, but I have only personally starting using that list recently and I am not actually entirely sure of the exact quality and frequency of curation.

**Comment by ScriptTiger** [comment]
Actually, this may not entirely fit here with the PyFunceble project, but more with the curation of @mitchellkrogza's Ultimate Hosts Blacklist project and related lists. Maybe there's a better repo for this issue, but just thought I'd put it here for discussion.

**Comment by dnmTX** [comment]
@ScriptTiger  the entire Ultimate Hosts Blacklist is filtered by PyFunceble project,just FYI.

**Comment by ScriptTiger** [comment]
@dnmTX, I am aware of that, but PyFunceble itself is more for checking the status/availability/reachability of domains. The Ultimate Hosts Blacklist is curated independently by other contributors, namely @mitchellkrogza, and PyFunceble is simply used to weed out dead hosts to keep the lists more highly curated, but PyFunceble does not necessarily give input towards whether hosts are "bad" or not. So that is why I said it does not necessarily fit with PyFunceble itself, but could maybe be thrown in as an add-on for specifically helping to curate the Ultimate Hosts Blacklist and related lists.

**Comment by dnmTX** [comment]
@ScriptTiger  on the contrary:

> The Ultimate Hosts Blacklist is curated independently by other contributors, namely @mitchellkrogza

Yes,and no. @mitchellkrogza has his own lists(Bad-Boyz,Phishing.Database etc.) that he's curating himself.The rest of the Ultimate Hosts Blacklist is just number of hosts lists put together(similar to StvenBlack's) which are curated by their repo owners and Mitch @mitchellkrogza or @funilrys doesn't  do any changes on them but to whitelist some domain in case the main curator can not be reached or whatever.
Take a look [HERE](https://travis-ci.org/Ultimate-Hosts-Blacklist)

> PyFunceble itself is more for checking the status/availability/reachability of domains

You are correct here and as i started to see many users is using it individually to filter their own lists and yes it's probably is a good idea your proposal to be placed as a option but without much deeper research,especially on that lists curation period i'm not really convinced that is suitable for such a huge project as the Ultimate Hosts Blacklist.

**Comment by ScriptTiger** [comment]
> ...without much deeper research,especially on that lists curation period i'm not really convinced that is suitable for such a huge project as the Ultimate Hosts Blacklist.

I'm still tracking changes now to check this. However, I can see that just over a period of 24 hours a significant number of changes have been made. It's part of AlienVault's Open Threat Exchange, OTX, so it also has expert contributors from around the world contributing to it and is used with many high-end threat defense technologies. I have actually been familiar with OTX for a long time now, but just recently realized they had a smaller list just for IPs. The OTX is definitely an extremely large project and obviously much more well-known than the Ultimate Hosts Blacklist itself.

**Comment by dnmTX** [comment]
@ScriptTiger  the quote part in your post above was based entirely of what you stated in your first post:

> I know that over time they do add and remove entries and it is curated to a degree, but I have only personally starting using that list recently and I am not actually entirely sure of the exact quality and frequency of curation.

....as i'm not really familiar with OTX and what they do. Anyway...i was just trying to give you some info here,not argue with you.
@funilrys  is in charge here so let's wait and see what he thinks about it and we'll go from there 😉

**Comment by ScriptTiger** [comment]
No, no, I completely get you, I am not arguing either, just providing more information, as you did raise a fair concern.

**Comment by funilrys** [comment]
Hello, sorry for the waiting time. I took some time to do put myself into OTX and the notion of IP reputation.

I think that it's a good idea to include such data. It makes sense to follow the reputation of IP/sub-domains.
Those data are not "bare data" but already curated data. Therefore, we don't have to worry about curation as their network is already doing their own curation.

I played with their API and it's promising. Unfortunately, I don't know what the rate limit of the OTX API is and I could not find any documentation about that.

--------------------------------------
For the context, I'm not against the evolution of PyFunceble.  In fact, we started this project with just status, when availability and reachability came later. Funceble was a project for me and @mitchellkrogza.

PyFunceble, on the other hand, is becoming a project for the Open Source Community. That's actually why I dropped Funceble. Our ideas got bigger and bigger which became unmanageable inside a single bash script.

The @dead-hosts infrastructure is an example of where we came from and where we are going. You can see out there that we are not alone anymore. List maintainer or single user are using PyFunceble for what it provides: "Status from several sources in 1 tool"

--------------------------------------

Back to OTX and the IP curation, it's really interesting because we could then, do more than what we currently do.  In fact, if we introduce this, we will still continue with the "Status from several sources in 1 tool" idea but in another level of curation for people who want to go beyond the standard checking.

I'm willing to introduce the IP curation as an option first for testing purposes in a future version of PyFunceble. But, I'm not sure if it's a good idea to provide that as default directly after the implementation.

About @ultimate-hosts-blacklist, I can't say if this option will be activated by default. But let's say it's possible but it does not depend on me alone. If we activate that, it will be on chosen input sources first. Not overall. For sure.

--------------------------------------

Now let's talk about implementation and they think that "sucks" for the grand-public.

Here is a list of ideas I got while playing with the OTX API:

* Flag a sub-domain which has a bad reputation out there as DANGEROUS or another shorter new flag.
* Flag a sub-domain which has a bad reputation out there as ACTIVE (Systematically).
* Provide a new scanning/testing mode which will then use the OTX API or other of their public the links (like the one @ScriptTiger provided) to detect "Malicious" entries/indicators.

I'm not sure about how I may implement this though :thinking:. Maybe you have better ideas.

There are 2 possibilities in the implementation.

1. Use their API to check a sub-domain/IP.
2. Parse the links and provide a systematical IP check against it.

Once the source is clear. Our problem will be: Where do we put that logic? or better said How do we make it available?

Here is part of my brainstorming:

1. It could be part of the [SPECIAL rules](https://pyfunceble.readthedocs.io/en/dev/columns/source.html#special) which will let people opt-out if they don't want it.
    * Not possible if we don't want to make it a default option yet.
2. It could be part of the Analytic outputs (not documented yet) which means that they don't necessarily influence the status. 
    * I don't think that this is the proper way as we know that they are Malicious anyway.
3. It can be part of a new MALICIOUS/SUSPICIOUS status source. (with a new switch to opt-out/in)
4. It can be a new checking method like what we have with `--syntax` but just for a malicious (origin) check.
5. It can be part of the default checking process. 

--------------------------------------

I need to stop before going too far. What do you think of those? I need your opinions!

Thanks again for everything, especially your time.

Cheers,
Nissar

**Comment by ScriptTiger** [comment]
> Unfortunately, I don't know what the rate limit of the OTX API is and I could not find any documentation about that.

To be honest I was just thinking of downloading the reputation.data file (http://reputation.alienvault.com/reputation.data) once at the start of running the script and then just checking the local file for each domain, so it would give you an unlimited rate limit. But if you want to dig into the actual API, which would definitely give you more options for what information you want to check, that's definitely a lot bigger than what I was thinking.

> There are 2 possibilities in the implementation.
> 1. Use their API to check a sub-domain/IP.
> 2. Parse the links and provide a systematical IP check against it.

As I said, my original thought was just what you stated in number 2., as this would be the easiest and fastest method without any limits since you're just accessing a local file and not making bulk API calls. But obviously the API can provide a lot more data to check against, but I can't really make any comments to that because I know that would be a whole new can of worms and I don't know how far you're willing to take this, although I know you usually like to take things as far as you can :P

> Here is part of my brainstorming:
> 
> 1. It could be part of the SPECIAL rules which will let people opt-out if they don't want it.
> 2. Not possible if we don't want to make it a default option yet.
> 3. It could be part of the Analytic outputs (not documented yet) which means that they don't necessarily influence the status.
> 4. I don't think that this is the proper way as we know that they are Malicious anyway.
> 5. It can be part of a new MALICIOUS/SUSPICIOUS status source. (with a new switch to opt-out/in)
> 6. It can be a new checking method like what we have with --syntax but just for a malicious (origin) check.
> 7. It can be part of the default checking process.

My vote would be 1, 3, or 4, with 4 being an optional switch, i.e. `--reputation`. But each of these obviously has a different amount of work associated with implementing them and, as I stated earlier, I'm not sure how far you want to take this. The key here being the ability to easily opt in and out. WHOIS, NSLOOKUP and HTTP status codes are all completely objective data sets, while it is possible to view reputation data as somewhat subject to an analyst's opinion. So for those looking for completely objective data, I can see how they might see this as a weakness if they are forced into including it.

**Comment by funilrys** [comment]
Hi @ScriptTiger and Happy New Year!

It's now implemented (in the dev branch at least). Just a question for you. As I don't want to spam the service, I'm creating a local copy of the link you provided and update it automatically if it's older than 24h at the time of execution.

Do you think that 24h is okay or should I reduce to 1h?

Cheers!

**Comment by ScriptTiger** [comment]
Lol, I'm sure 24 hours is fine. To be honest, I update mine a lot less. The really bad actors are always going to be on the list, it's just newcomers and temporary threats that pop in and out that keep the list active on an hourly basis. You only really need to update it that often if you're providing network edge security, but for you purposes it's fine.

I have also been keeping an eye on Cisco Talos' list:
https://talosintelligence.com/documents/ip-blacklist

They use it with Snort, a super popular open-source IDS/IPS. It's only a proof of concept right now and just a small subset of their actual data, so you may want to wait before thinking about using it.

**Comment by spirillen** [comment]
~~Self note: Own issue [here](https://www.mypdns.org/T582)~~
