### ISSUE TITLE
Feature request - Testing of urls

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/PyFunceble#7]
Would be great to see a feature added to achieve the following

- test a full url (or input file or urls) not just the domains

- test only for http status codes 200 OK, 404 NOT FOUND, 410 GONE and 403 FORBIDDEN (no whois checks so will be much faster)

- produce simple output files of URLs ACTIVE, URLS INACTIVE

**Comment by funilrys** [comment]
The feature has been introduced with https://github.com/funilrys/PyFunceble/commit/38509e03c4e1e87259d081eb9715e0e1b3cd9dd4.

P.S: Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/38509e03c4e1e87259d081eb9715e0e1b3cd9dd4 will be merged to master.

**Comment by funilrys** [comment]
Please note @mitchellkrogza  and others who may use this feature:

We use the same information as [List of categorized HTTP status code](https://github.com/funilrys/PyFunceble/wiki/Columns#list-of-categorized-http-status-code).

* [As active](https://github.com/funilrys/PyFunceble/wiki/Columns#as-active) returns `ACTIVE`
* [As potentially active](https://github.com/funilrys/PyFunceble/wiki/Columns#as-potentially-active) returns `ACTIVE`
* [As inactive or potentially inactive](https://github.com/funilrys/PyFunceble/wiki/Columns#as-inactive-or-potentially-inactive) returns `INACTIVE`
* If the domain is not valid (please report to [documentation](https://github.com/funilrys/PyFunceble/wiki/Columns#invalid)) we return `INVALID`
   * We do not check against our `iana-domains-db.json`
