### ISSUE TITLE
Add an auto mode for multiprocessing

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#78]
**Is your feature request related to a problem? Please describe.**
If, by mistake e.g. due to a typo too many threads, the whole program hangs itself and at random times stops working. 

**Describe the solution you'd like**
A possible solution would be an auto mode which automatically sets the threads according to the number of cores in the processor.

For example, if you write "auto" in the configuration file.
```
maximal_processes: auto
multiprocess: true
```
For example, if you have 20 processor cores, it should automatically make 20 threads.

**Comment by funilrys** [comment]
@ZeroDot1, this is not an issue if you use PyFunceble from the CLI. Indeed if you run the following:

```
$ PyFunceble -f my_awesome_list -m -p 20
```

20 processes will be created/used.

But, if you run the following

```
$ PyFunceble -f my_awesome_list -m 
```

PyFunceble will automatically fit/follow the number of available CPU cores.

**Comment by funilrys** [comment]
The documentation states it @ZeroDot1 

- https://pyfunceble.readthedocs.io/en/dev/configuration/index.html#maximal-processes 
- https://pyfunceble.readthedocs.io/en/dev/components/multiprocessing.html#number-of-processes-to-create

**Comment by funilrys** [comment]
TODO: Add something about that in the help.

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/PyFunceble/commit/e15a87c5f7db89c98b7aefc3a65de338e2d85530.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/e15a87c5f7db89c98b7aefc3a65de338e2d85530 will be merged to master.**

**Comment by spirillen** [comment]
Let me throw one in....

As `-m` multiprocessing is working best (default to) sql backend, shouldn't the default `-m` be something like 

```
if $(nproc) => 4
then -m == $(nproc -2)
else
-m == $(-p 1)
fi
```

Explanation:

First you need free resources to the DB
Second you might like to have a free thread to you other work (system-processes).

PS: Thanks for reminding me @ZeroDot1 I had this on my mind around christmas

**Comment by funilrys** [comment]
@spirillen I do agree, but in the case `you might like to have a free thread to you other work`, people should then set their own value!  (And most do when they see, that they can't use their machine anymore!)

I'm not ready yet to take on such a change. I especially have to think about people or robots who rely on the current behavior because PyFunceble is running on its very own VM.

Will probably come back in the future when this topic comes back. Do not delete your comment, please 😊!

Stay safe and healthy!
Nissar
