### ISSUE TITLE
Suggestion: Numeric sortorder => Human numeric

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#96]
As I was testing the [^mkt([0-9]{1,5})\.com$](https://www.mypdns.org/T902). I couldn't help not notice that the sort order was sorted in machine order, not the human sort order

```
1..10
11..100
101..1000
etc.
```

You can see the full paste here: <https://www.mypdns.org/P9> but you probably already caught the drift in this one :smile: :wink: 

**Priority**: Very low, barely within the numeric+ line :laughing:

**Comment by funilrys** [comment]
Fixed by https://github.com/funilrys/PyFunceble/commit/3e7c47f163feac8767a4326c1005fd29dc8462c2.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/3e7c47f163feac8767a4326c1005fd29dc8462c2 will be merged to master.**
